/**
 * @module AutoImport
 *
 * Automatic component importing for MetaOwl applications.
 */

import { globSync } from 'glob'
import { basename, dirname, extname, relative, resolve } from 'node:path'
import type { Dirent } from 'node:fs'

type ComponentImportMap = Map<string, string>

interface ScanOptions {
  pattern?: string
}

interface AutoImportPluginOptions {
  enabled?: boolean
  componentsDir?: string
  pattern?: string
}

interface AliasConfig {
  [key: string]: string
}

interface TransformResult {
  code: string
  map: null
}

interface PluginConfigShape {
  resolve?: {
    alias?: AliasConfig
  }
}

let importMap: ComponentImportMap | null = null

export function generateComponentMap(componentsDir: string, pattern = '*.js'): ComponentImportMap {
  const map: ComponentImportMap = new Map()
  const globPattern = pattern.includes('/') ? pattern : `${componentsDir}/${pattern}`
  const files = globSync(globPattern)

  for (const file of files) {
    if (file.includes('.test.') || file.includes('.spec.')) continue

    const name = getComponentName(file)
    if (!name) continue

    const importPath = `/@components/${relative(componentsDir, file).replace(/\\/g, '/')}`
    map.set(name, importPath)
  }

  return map
}

function getComponentName(filePath: string): string {
  const ext = extname(filePath)
  const base = basename(filePath, ext)

  if (basename(filePath) === base + ext) {
    return base
  }

  const dir = relative(process.cwd(), filePath).split('/')
  if (base === 'index' && dir.length > 1) {
    return toPascalCase(dir[dir.length - 2] ?? '')
  }

  return toPascalCase(base)
}

function toPascalCase(str: string): string {
  return str
    .replace(/[-_](.)/g, (_, char: string) => char.toUpperCase())
    .replace(/^[a-z]/, (char) => char.toUpperCase())
}

export async function scanComponents(componentsDir: string, options: ScanOptions = {}): Promise<string[]> {
  const { pattern: _pattern = '*.js' } = options
  const absoluteDir = resolve(componentsDir)
  const fs = await import('node:fs/promises')
  const { join } = await import('node:path')
  const components: string[] = []

  async function scanDir(dir: string): Promise<void> {
    try {
      const entries = await fs.readdir(dir, { withFileTypes: true }) as Dirent[]

      for (const entry of entries) {
        const fullPath = join(dir, entry.name)

        if (entry.isDirectory()) {
          await scanDir(fullPath)
        } else if (entry.isFile() && entry.name.endsWith('.js')) {
          if (entry.name.includes('.test.') || entry.name.includes('.spec.')) continue

          const name = getComponentName(fullPath)
          if (name && !components.includes(name)) {
            components.push(name)
          }
        }
      }
    } catch {
      // Directory doesn't exist or can't be read
    }
  }

  await scanDir(absoluteDir)
  return components
}

export async function generateComponentDts(components: string[], outputPath: string): Promise<void> {
  const { mkdirSync, writeFileSync } = await import('node:fs')
  const dir = dirname(outputPath)
  mkdirSync(dir, { recursive: true })

  const declarations = components
    .map((name) => `  ${name}: typeof import('./components/${name}/${name}.js').default`)
    .join('\n')

  const content = `// Auto-generated by metaowl - do not edit\ndeclare module '@metaowl/components' {\n${declarations}\n}\n`
  writeFileSync(outputPath, content, 'utf-8')
}

export function generateImports(componentMap: ComponentImportMap): string {
  const lines: string[] = []
  for (const [name, path] of componentMap) {
    lines.push(`import ${name} from '${path}'`)
  }
  return lines.join('\n')
}

export function generateComponentsObject(componentMap: ComponentImportMap): string {
  const entries = Array.from(componentMap.keys())
    .map((name) => `  ${name}`)
    .join(',\n')
  return `{\n${entries}\n}`
}

export function createAutoImportPlugin(options: AutoImportPluginOptions = {}): {
  name: string
  enforce: 'pre'
  config: (config: PluginConfigShape) => void
  transform: (code: string, id: string) => TransformResult | null
} | null {
  const {
    enabled = false,
    componentsDir = 'src/components',
    pattern = '**/*.js'
  } = options

  if (!enabled) {
    return null
  }

  importMap = generateComponentMap(componentsDir, `${componentsDir}/${pattern}`)

  return {
    name: 'metaowl:auto-import',
    enforce: 'pre',

    config(config: PluginConfigShape): void {
      config.resolve ||= {}
      config.resolve.alias ||= {}
      config.resolve.alias['/@components'] = resolve(process.cwd(), componentsDir)
    },

    transform(code: string, id: string): TransformResult | null {
      if (!id.includes('/pages/') || !/\.[jt]s$/.test(id)) {
        return null
      }

      if (!code.includes('/* auto-import */') && !code.includes('// auto-import')) {
        return null
      }

      if (!importMap) {
        return null
      }

      const imports = generateImports(importMap)
      const componentsObj = generateComponentsObject(importMap)

      let transformed = imports + '\n\n' + code

      if (transformed.includes('extends Component')) {
        transformed = transformed.replace(
          /(class\s+\w+\s+extends\s+Component\s*\{)/,
          `$1\n  static components = ${componentsObj}\n`
        )
      }

      return { code: transformed, map: null }
    }
  }
}

export function registerAutoImport(name: string, path: string): void {
  if (!importMap) {
    importMap = new Map()
  }
  importMap.set(name, path)
}

export function getAutoImportMap(): ComponentImportMap | null {
  return importMap ? new Map(importMap) : null
}

export function clearAutoImports(): void {
  importMap = null
}