/**
 * @module AutoImport
 *
 * Automatic component importing for MetaOwl applications.
 *
 * Features:
 * - Auto-discovers components from src/components/
 * - Generates import statements at build time
 * - Optional - disabled by default
 *
 * Configuration in vite.config.js:
 *   metaowlConfig({
 *     autoImport: {
 *       enabled: true,
 *       componentsDir: 'src/components',
 *       pattern: '*.js'
 *     }
 *   })
 *
 * Usage:
 * - Components are automatically available in templates
 * - No manual import needed
 */

import { globSync } from 'glob'
import { resolve, relative, basename, extname, dirname } from 'path'

/**
 * Registry of auto-discovered components.
 */
let _importMap = null

/**
 * Generate component import map from directory.
 *
 * @param {string} componentsDir - e.g. 'src/components'
 * @returns {Map<string, string>} Map of PascalCase names to import paths
 */
export function generateComponentMap(componentsDir, pattern = '*.js') {
  const map = new Map()
  const globPattern = pattern.includes('/') ? pattern : `${componentsDir}/${pattern}`
  const files = globSync(globPattern)

  for (const file of files) {
    if (file.includes('.test.') || file.includes('.spec.')) continue

    const name = getComponentName(file)
    if (!name) continue

    const importPath = `/@components/${relative(componentsDir, file).replace(/\\/g, '/')}`
    map.set(name, importPath)
  }

  return map
}

function getComponentName(filePath) {
  const ext = extname(filePath)
  const base = basename(filePath, ext)
  
  if (basename(filePath) === base + ext) {
    return base
  }
  
  const dir = relative(process.cwd(), filePath).split('/')
  if (base === 'index' && dir.length > 1) {
    return toPascalCase(dir[dir.length - 2])
  }
  
  return toPascalCase(base)
}

function toPascalCase(str) {
  return str
    .replace(/[-_](.)/g, (_, char) => char.toUpperCase())
    .replace(/^[a-z]/, char => char.toUpperCase())
}

/**
 * Scan components directory for component files.
 *
 * @param {string} componentsDir - Directory to scan
 * @param {object} options - Options
 * @param {string} options.pattern - Glob pattern
 * @returns {Promise<string[]>} Array of component names
 */
export async function scanComponents(componentsDir, options = {}) {
  const { pattern = '*.js' } = options
  const absoluteDir = resolve(componentsDir)
  const fs = await import('fs/promises')
  const { join } = await import('path')

  const components = []

  async function scanDir(dir) {
    try {
      const entries = await fs.readdir(dir, { withFileTypes: true })

      for (const entry of entries) {
        const fullPath = join(dir, entry.name)

        if (entry.isDirectory()) {
          // Recursively scan subdirectories
          await scanDir(fullPath)
        } else if (entry.isFile() && entry.name.endsWith('.js')) {
          // Skip test files
          if (entry.name.includes('.test.') || entry.name.includes('.spec.')) continue

          const name = getComponentName(fullPath)
          if (name && !components.includes(name)) {
            components.push(name)
          }
        }
      }
    } catch {
      // Directory doesn't exist or can't be read
    }
  }

  await scanDir(absoluteDir)
  return components
}

/**
 * Generate TypeScript declarations file for components.
 *
 * @param {string[]} components - Array of component names
 * @param {string} outputPath - Path to write .d.ts file
 * @returns {Promise<void>}
 */
export async function generateComponentDts(components, outputPath) {
  const { writeFileSync, mkdirSync } = await import('fs')
  const { join } = await import('path')

  // Ensure directory exists
  const dir = dirname(outputPath)
  mkdirSync(dir, { recursive: true })

  const declarations = components.map(name =>
    `  ${name}: typeof import('./components/${name}/${name}.js').default`
  ).join('\n')

  const content = `// Auto-generated by metaowl - do not edit\ndeclare module '@metaowl/components' {\n${declarations}\n}\n`

  writeFileSync(outputPath, content, 'utf-8')
}

export function generateImports(componentMap) {
  const lines = []
  for (const [name, path] of componentMap) {
    lines.push(`import ${name} from '${path}'`)
  }
  return lines.join('\n')
}

export function generateComponentsObject(componentMap) {
  const entries = Array.from(componentMap.keys())
    .map(name => `  ${name}`)
    .join(',\n')
  return `{\n${entries}\n}`
}

export function createAutoImportPlugin(options = {}) {
  const {
    enabled = false,
    componentsDir = 'src/components',
    pattern = '**/*.js'
  } = options

  if (!enabled) {
    return null
  }

  _importMap = generateComponentMap(componentsDir, `${componentsDir}/${pattern}`)

  return {
    name: 'metaowl:auto-import',
    enforce: 'pre',

    config(config) {
      config.resolve ||= {}
      config.resolve.alias ||= {}
      config.resolve.alias['/@components'] = resolve(process.cwd(), componentsDir)
    },

    transform(code, id) {
      if (!id.includes('/pages/') || !/\.[jt]s$/.test(id)) {
        return null
      }

      if (!code.includes('/* auto-import */') && !code.includes('// auto-import')) {
        return null
      }

      const imports = generateImports(_importMap)
      const componentsObj = generateComponentsObject(_importMap)

      let transformed = imports + '\n\n' + code

      if (transformed.includes('extends Component')) {
        transformed = transformed.replace(
          /(class\s+\w+\s+extends\s+Component\s*\{)/,
          `$1\n  static components = ${componentsObj}\n`
        )
      }

      return { code: transformed, map: null }
    }
  }
}

export function registerAutoImport(name, path) {
  if (!_importMap) {
    _importMap = new Map()
  }
  _importMap.set(name, path)
}

export function getAutoImportMap() {
  return _importMap ? new Map(_importMap) : null
}

export function clearAutoImports() {
  _importMap = null
}
